In [ ]:
#wordcloud-In datascrapping
#DTM matrix

In [3]:
import string
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from matplotlib import pyplot as plt
import pandas as pd

In [5]:
import os
os.chdir('D:\Manipal Pro learn\Term1\EDA\Dataset')

In [6]:
moditweets = pd.read_excel('narendramodi_tweets.xlsx')
moditweets.head()

,id,retweets_count,favorite_count,created_at,text,lang,retweeted,followers_count,friends_count,hashtags_count,description,location,background_image_url,source
0,826000000000000000,1406,4903,2017-01-31 11:00:00,The President's address wonderfully encapsulat...,en,False,26809964,1641,1,Prime Minister of India,India,http://pbs.twimg.com/profile_background_images...,Twitter Web Client
1,826000000000000000,907,2877,2017-01-31 10:59:00,Rashtrapati Ji's address to both Houses of Par...,en,False,26809964,1641,0,Prime Minister of India,India,http://pbs.twimg.com/profile_background_images...,Twitter Web Client
2,826000000000000000,694,0,2017-01-31 10:52:00,RT @PMOIndia: Empowering the marginalised. htt...,en,False,26809964,1641,0,Prime Minister of India,India,http://pbs.twimg.com/profile_background_images...,Twitter Web Client
3,826000000000000000,666,0,2017-01-31 10:52:00,RT @PMOIndia: Commitment to welfare of farmers...,en,False,26809964,1641,0,Prime Minister of India,India,http://pbs.twimg.com/profile_background_images...,Twitter Web Client
4,826000000000000000,716,0,2017-01-31 10:52:00,RT @PMOIndia: Improving the quality of life fo...,en,False,26809964,1641,0,Prime Minister of India,India,http://pbs.twimg.com/profile_background_images...,Twitter Web Client

In [7]:
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to C:\Users\Arun
[nltk_data]     Kumar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [8]:
tweettext = moditweets[['text']]
tweettext.head()

                                                text
0  The President's address wonderfully encapsulat...
1  Rashtrapati Ji's address to both Houses of Par...
2  RT @PMOIndia: Empowering the marginalised. htt...
3  RT @PMOIndia: Commitment to welfare of farmers...
4  RT @PMOIndia: Improving the quality of life fo...

In [9]:
#Number of words in each row
tweettext['count'] = tweettext['text'].apply(lambda x : len(x.split()))
tweettext.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

                                                text  count
0  The President's address wonderfully encapsulat...     14
1  Rashtrapati Ji's address to both Houses of Par...     16
2  RT @PMOIndia: Empowering the marginalised. htt...      6
3  RT @PMOIndia: Commitment to welfare of farmers...      8
4  RT @PMOIndia: Improving the quality of life fo...     11

In [10]:
#Step1 and 2 Converting to lower case and replacing special character

tweettext['clean_txt'] = tweettext['text'].str.lower().str.replace('[^a-z ]','')
tweettext.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,text,count,clean_txt
0,The President's address wonderfully encapsulat...,14,the presidents address wonderfully encapsulate...

In [11]:
# Step4  Removing the stopwords

stop = stopwords.words('english')
stop.extend(['amp','modi','narendra','pmo'])

def sw(txt):
    txt = [word for word in txt.split() if word not in stop]
    return " ".join(txt)

tweettext['text_without_stop'] = tweettext['clean_txt'].apply(sw)

print(tweettext['text_without_stop'][0])
print(tweettext['clean_txt'][0])

presidents address wonderfully encapsulated indias strengths aspirations potential efforts towards transformingindia
the presidents address wonderfully encapsulated indias strengths aspirations potential amp the efforts towards transformingindia

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [12]:
# starting the count vector

vec = CountVectorizer(min_df=0.01,max_df=0.9)  #min_df is minimum percentage of time words atleast should be used
            #max_df is maximum percentage of time words can be used(if used more than max_df then remove it)
vec.fit(tweettext['text_without_stop'])

#creating dict of items in matrix (to know column numbers of each word) optional

dic = vec.vocabulary_.items()
dic

dict_items([('indias', 52), ('efforts', 27), ('towards', 130), ('transformingindia', 131), ('extensive', 30), ('rt', 99), ('pmoindia', 89), ('farmers', 32), ('life', 63), ('poor', 90), ('government', 37), ('govt', 38), ('india', 50), ('various', 134), ('lives', 64), ('every', 29), ('many', 69), ('bharat', 8), ('corruption', 18), ('one', 84), ('birth', 9), ('anniversary', 4), ('great', 39), ('th', 121), ('greetings', 40), ('mannkibaat', 68), ('help', 46), ('day', 19), ('celebrations', 12), ('joined', 58), ('meeting', 72), ('proud', 95), ('best', 7), ('world', 142), ('make', 67), ('work', 141), ('young', 146), ('spoke', 112), ('today', 128), ('join', 57), ('youth', 147), ('benefit', 6), ('several', 104), ('key', 60), ('people', 87), ('development', 21), ('time', 126), ('state', 113), ('years', 143), ('bjp', 11), ('well', 138), ('tributes', 132), ('congratulations', 16), ('shri', 107), ('singh', 108), ('always', 3), ('support', 116), ('thank', 122), ('pm', 88), ('wishes', 139), ('special', 111), ('president', 92), ('happy', 42), ('visit', 136), ('ties', 125), ('us', 133), ('cooperation', 17), ('sector', 101), ('discussions', 23), ('wishing', 140), ('national', 79), ('role', 98), ('also', 2), ('new', 82), ('across', 0), ('share', 105), ('strong', 114), ('forward', 33), ('delighted', 20), ('let', 62), ('ensure', 28), ('mp', 75), ('meet', 71), ('international', 54), ('society', 109), ('progress', 94), ('made', 66), ('pray', 91), ('growth', 41), ('shared', 106), ('highlighted', 47), ('via', 135), ('thoughts', 124), ('app', 5), ('programme', 93), ('need', 81), ('families', 31), ('peace', 86), ('talked', 118), ('nations', 80), ('remember', 96), ('indian', 51), ('nation', 78), ('citizens', 13), ('soldiers', 110), ('take', 117), ('may', 70), ('good', 36), ('health', 43), ('ji', 56), ('cm', 14), ('held', 45), ('discussed', 22), ('economic', 26), ('agriculture', 1), ('together', 129), ('interaction', 53), ('talks', 119), ('summit', 115), ('leaders', 61), ('yoga', 144), ('technology', 120), ('narendramodi', 77), ('glad', 35), ('see', 102), ('dr', 25), ('issues', 55), ('part', 85), ('water', 137), ('met', 73), ('must', 76), ('give', 34), ('minister', 74), ('karyakartas', 59), ('birthday', 10), ('long', 65), ('healthy', 44), ('come', 15), ('https', 48), ('nm', 83), ('thanks', 123), ('sandeshsoldiers', 100), ('diwali', 24), ('sent', 103), ('rio', 97), ('tirangayatra', 127), ('idy', 49), ('yogaday', 145)])

In [13]:
#creating DTM matrix

x = vec.fit_transform(tweettext['text_without_stop'])
x

<2987x148 sparse matrix of type '<class 'numpy.int64'>'
	with 9286 stored elements in Compressed Sparse Row format>

In [14]:
#convert DTM to dataframe
vec = CountVectorizer()
vec.fit(tweettext['text_without_stop'])
x = vec.fit_transform(tweettext['text_without_stop'])
DTM  = pd.DataFrame(x.toarray(),columns=vec.get_feature_names())
DTM.head()

,aabhar,aadhaar,aadhar,aajtak,aamirkhan,aanandmayi,aap,aawas,aazadisaal,abdel,...,zaidi,zayed,zeal,zero,zhejiang,ziara,zimbabwe,zone,zones,zuma
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
DTM.sum().nlargest(5)

rt          573
india       365
people      203
pm          169
pmoindia    145
dtype: int64